package com.palmwifi.ktv.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.palmwifi.ktv.bean.FavSong;
import com.palmwifi.ktv.bean.Song;

import com.palmwifi.ktv.db.FavSongDao;
import com.palmwifi.ktv.db.SongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favSongDaoConfig;
    private final DaoConfig songDaoConfig;

    private final FavSongDao favSongDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favSongDaoConfig = daoConfigMap.get(FavSongDao.class).clone();
        favSongDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        favSongDao = new FavSongDao(favSongDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(FavSong.class, favSongDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        favSongDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public FavSongDao getFavSongDao() {
        return favSongDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
